# Generated by Django 6.0.5 on 2026-06-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMaster',
            fields=[
                ('patient_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(default='Unknown', max_length=20)),
                ('chronic_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.CharField(default='No known drug allergies', max_length=250)),
                ('family_medical_history', models.TextField(blank=True, null=True)),
                ('lifestyle_habits', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField()),
                ('date_of_discharge', models.DateField()),
                ('attending_physician', models.CharField(max_length=100)),
                ('primary_diagnosis', models.CharField(max_length=255)),
                ('reason_for_admission', models.TextField()),
                ('hospital_course_summary', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=100)),
                ('tumor_size_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pathology_details', models.TextField(blank=True, null=True)),
                ('lab_abnormalities', models.TextField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='patients.hospitalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='DischargeCarePlan',
            fields=[
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.hospitalencounter')),
                ('surgical_history', models.TextField(blank=True, null=True)),
                ('discharge_medications', models.TextField()),
                ('chemotherapy_regimen', models.TextField(blank=True, null=True)),
                ('radiation_regimen', models.TextField(blank=True, null=True)),
                ('follow_up_appointments', models.TextField()),
                ('activity_restrictions', models.TextField()),
                ('dietary_hydration_directives', models.TextField()),
                ('urgent_warning_signs', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster')),
            ],
        ),
    ]
