# Generated by Django 6.0.5 on 2026-06-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalencounter',
            name='attending_physician',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
