# Generated by Django 6.0.5 on 2026-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelPatientRecord',
            fields=[
                ('medical_record_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='MRN')),
                ('patient_name', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('date_of_admission', models.CharField(max_length=20)),
                ('date_of_discharge', models.CharField(max_length=20)),
                ('attending_physician', models.CharField(max_length=255)),
                ('primary_diagnosis', models.CharField(max_length=255)),
                ('medical_history_summary', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Excel Patient Records',
            },
        ),
    ]
