# Generated by Django 6.0.5 on 2026-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_hospitalencounter_attending_physician'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotinquirylog',
            options={'verbose_name': 'Chatbot Inquiry Log', 'verbose_name_plural': 'Chatbot Inquiry Logs'},
        ),
        migrations.AlterModelOptions(
            name='excelpatientrecord',
            options={'verbose_name': 'Excel Patient Record', 'verbose_name_plural': 'Excel Patient Records'},
        ),
        migrations.RemoveField(
            model_name='excelpatientrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='excelpatientrecord',
            name='attending_physician',
            field=models.CharField(blank=True, default='Unassigned', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='excelpatientrecord',
            name='medical_record_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hospitalencounter',
            name='attending_physician',
            field=models.CharField(default='General Staff', max_length=100),
        ),
    ]
