# Generated by Django 6.0.5 on 2026-06-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_chatbotinquirylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelpatientrecord',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excelpatientrecord',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
