# Generated by Django 6.0.5 on 2026-07-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelfCheckMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('fitness_goal', models.CharField(choices=[('LOSE', 'Weight Loss'), ('MAINTAIN', 'Maintenance'), ('GAIN', 'Muscle Gain')], max_length=10)),
                ('calculated_bmi', models.FloatField(blank=True, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=30, null=True)),
                ('recommended_calories', models.IntegerField(blank=True, null=True)),
                ('diet_plan_markdown', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
